export const GET = {
  START: 'GET_USER/START',
  SUCCESS: 'GET_USER/SUCCESS',
  FAIL: 'GET_USER/FAIL',
}

export const GET_LIST = {
  START: 'GET_USER_LIST/START',
  SUCCESS: 'GET_USER_LIST/SUCCESS',
  FAIL: 'GET_USER_LIST/FAIL',
}
